export default {
    name: "Ivan Macabontoc",
    github: "https://github.com/Jushiro012623",
    linkedin: "https://www.linkedin.com/in/ivanmacabontoc/",
    email: "ivanallen64@gmail.com",
    profile_path: "/assets/me.jpg",
    career_role: "Software Developer",
    tagline:"",
    address: "Manila, Metro-Manila, PH",
    phone: '+63-912-5279-754',
    career_desc: "I specialize in building scalable, maintainable web applications using modern frontend and backend technologies",
    tech_stack: [
        {src: "/assets/laravel.svg", alt: "laravel icon"},
        {src: "/assets/react.svg", alt: "react icon"},
        {src: "/assets/jest.svg", alt: "jest icon"},
        {src: "/assets/docker.svg", alt: "docker icon"},
        {src: "/assets/dotnet.svg", alt: "dotnet icon"},
        {src: "/assets/git.svg", alt: "git icon"},
        {src: "/assets/nextjs.svg", alt: "nextjs icon"},
        {src: "/assets/node.svg", alt: "node icon"},
        {src: "/assets/typescript.svg", alt: "typescript icon"},
        {src: "/assets/vite.svg", alt: "vite icon"},
        {src: "/assets/kubernetes.svg", alt: "kubernetes icon"},
        {src: "/assets/jenkins.svg", alt: "jenkins icon"},
        {src: "/assets/express.svg", alt: "express icon"},
        {src: "/assets/py.svg", alt: "python icon"},
        {src: "/assets/redux.svg", alt: "redux icon"},
        {src: "/assets/tailwind.svg", alt: "tailwind icon"},
        {src: "/assets/angular.svg", alt: "angular icon"},
        {src: "/assets/nestjs.svg", alt: "nestjs icon"},
    ],
    projects: [
        {
            title: "BYB Themed Park",
            description: "Developed the backend for a theme park ticketing system with APIs for bookings, validation, and ticket processing.",
            src: "byb.png",
            url: "https://tickets.blueskythemepark.ph/",
            color: "gradient-2",
            img: "shadow-lg",
            preview: "LIVE",
            stacks: [ "laravel.svg", 'tailwind.svg', 'vite.svg', 'typescript.svg', 'react.svg'],
        },
        {
            title: "Oceanwide Enrollment",
            description: "Developed the backend APIs for an online enrollment system with student management and secure data processing.",
            src: "oceanwide.png",
            url: "https://oceanwide-enrollment.pisopay.com.ph/",
            color: "gradient-2",
            img: "shadow-lg",
            preview: "LIVE",
            stacks: [ "laravel.svg", 'tailwind.svg', 'vite.svg'],
        },
        {
            title: "Barangay Management",
            description: "Built a full-stack web platform for Barangay management, including dashboards, forms, and backend services for residents and councils.",
            src: "bms.png",
            url: "https://bms-mock.vercel.app/login",
            color: "gradient-3",
            img: "shadow-lg shadow-neutral-800",
            preview: "DEMO",
            stacks: [ "react.svg", "nestjs.svg", 'tailwind.svg', 'typescript.svg'],
        },
        {
            title: "Turismo Car Rental",
            description: "Designed and developed a premium car rental site with responsive layouts, interactive UI, and engaging product displays.",
            src: "TURISMO.png",
            url: "https://turismo-car-rental.vercel.app",
            color: "gradient-1",
            img: "shadow-lg shadow-neutral-800",
            preview: "LIVE",
            stacks: [ "mongodb.svg", 'tailwind.svg', 'typescript.svg', 'nextjs.svg],
        },
        {
            title: "AI Smart Resume Analyzer",
            description: "Developed a smart resume analyzer that evaluates resumes, provides a score, and gives actionable tips for improvement.",
            src: "resume-analyzer.png",
            url: "https://infinity-ai-resume-analyzer.vercel.app",
            color: "gradient-1",
            img: "shadow-lg",
            preview: "DEMO",
            stacks: [ "react.svg", "node.svg", 'tailwind.svg', 'typescript.svg'],
        },
        {
            title: "IPhone 15 Website",
            description: "Cloned an iPhone 15 website with responsive design, interactive UI elements, and smooth animations to mimic the official site experience.",
            src: "iphone.png",
            url: "https://iphone-clone-green.vercel.app/",
            color: "gradient-1",
            img: "shadow-lg",
            preview: "DEMO",
            stacks: [ "react.svg", 'tailwind.svg', 'typescript.svg'],
        }

    ],
    experience: [
        {
            start: "June 2024",
            company: "Pisopay.com Inc",
            end: "Present",
            desc: "Developed scalable applications and core systems such as a payment gateway, admin dashboard, and authentication service, designing robust APIs and database structures to ensure secure, high-performance workflows and efficient data flow across the platform. ",
            logo: "/assets/pisopayTM.png",
            position: "Backend Developer",
            logoAlt: "PPAY LOGO"
        },
        {
            start: "January 2023",
            company: "DepEd - Manila",
            end: "May 2023",
            desc: "Designed and developed a responsive budget management system as a Frontend Developer, creating intuitive interfaces and ensuring smooth user experience. ",
            logo: "/assets/deped.webp",
            position: "Frontend Developer - Intern",
            logoAlt: "DEPED LOGO"
        }
    ]
}
